services:
  api:
    volumes:
      - ${USERPROFILE}/.aws:/aws:ro
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /aws/credentials
      AWS_CONFIG_FILE: /aws/config
      AWS_EC2_METADATA_DISABLED: "true"

  worker:
    volumes:
      - ${USERPROFILE}/.aws:/aws:ro
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /aws/credentials
      AWS_CONFIG_FILE: /aws/config
      AWS_EC2_METADATA_DISABLED: "true"
